### ISSUE TITLE
Project "Functor"

### ISSUE THREAD

**Issue by Nhlest** [Nhlest/shikataganai#17]
## Implement an extensible, future-proof, multiplayer-first system for Functor synchronisation / access control / automatic serialisation / deserialisation.
**Functor** is an ECS component attached to a block entity with certain functionality associated with it. Systems might iterate over functors (via ECS queries) to gather information required for that system's logic, functors might move with blocks and be stored in block storage alongside those blocks. Not all functors must be in clients memory at all time, for example a chest's internal inventory is only viable to be synchronised among client-server for when that client is interacting with that chest because otherwise the contents of that chest do not affects client's rendering in any way. 
On the other hand a functor for, for example, a button or a lever (which represents that button's state) must be synchronised with all players within that lever's event horizon. Some functors must have exclusive locks, for example, if a player is interacting with a chest - that chest's inventory must be locked and inaccessible (and invalidated) for all other players who might request access to it / might have that chest's outdated inventory in their memory.

### Stage 1: Cleanup
- [ ] Remove all code related to outdated proof of concept functor system. 
### Stage 2: Functor lock / invalidation / synchronisation
- [ ] Track all functors in client's memories, track locks, invalidate outdated functors
- [ ] Create a universal way to address functors. A simple block coordinate is not enough because a block entity might have multiple functors attached to it. (An enum?)
### Stage 3: Client functor request
- [ ] Automatically send all functors that must be in client memory at all times upon chunk loading (Such as button / level state, functors that affect player's rendering), add those functors to tracked list for further update if the state is changed in server memory.
- [ ] Fulfill player's requests for new functors, deny if the functor is locked, invalidate locks for "dead" clients.
- [ ] If a block is harvested / functor no longer exists - invalidate the functor and gracefully cease the interaction at client side.
### Stage 4: Client interactions with functors
- [ ] A universal way for client to change a state of a functor. Press a button / add/remove/swap items in internal inventories
- [ ] Sync those changes (if needed, if tracked) with other players.
### Stage 5: A gameplay PoC with functors.
- [ ] A lever
- [ ] A chest
- [ ] A crafting station that displays / renders its internal grid for all players.
